# Generated by Django 6.1 on 2026-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('paises', 'Paises'), ('deportes', 'Deportes'), ('educacion', 'Educacion'), ('cocina', 'Cocina'), ('historia', 'Historia'), ('ciencia', 'Ciencia'), ('curiosidades', 'Curiosidades')], default='curiosidades', max_length=20),
        ),
    ]
